### PR TITLE
Fixes unspecified region

### PR DESCRIPTION
**Pull request by tijko**
Add `region` field in the configuration file.

I'm not sure if you have any preferences here.  You could leave an empty string field and make a note in the `README.md` that the user needs to fill in prior to running.

### CODE REVIEW

**Comment by tbenthompson** [comment]
I use a AWS config file to set the region. For example, my `~/.aws/config` contains:

```
[default]
output = text
region = us-east-1
```

I think this is a pretty typical way of using the AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

I'm not at all opposed to the additional of an optional region parameter in the config file. But, it should definitely be optional. So, that would require some small edits to this pull request.

**Comment by tijko** [comment]
If that's the case why not put your `config` in the repository too?

It's not much either way, config file added or not.

I liked the idea of this project and had a few ideas that could add some extra functionality.

**Comment by tbenthompson** [comment]
I'd prefer not to put a `config` file in the repo, because others may want to use a different region. Also, the `config` file is normally user-global, so I think that would create unexpected behavior for more people than it would help.

I'd be super excited to hear your suggestions. Feel free to add them as comments to this pull request or to open other issues or however else you'd like to discuss!

**Comment by tijko** [comment]
My first thought was a mention of how your `config` is setup in the `README.md`.  Putting the entire configuration file isn't great I understand not wanting to drop it in.

I'm on mobile right now and will push some commits when back in front of my machine.

**Comment by tijko** [comment]
I checked out the link you provided and can see the issue was that I wasn't even using `aws-cli` prior to running.  Up until this point I had just the credentials file for `boto3` and no `config`.

`aws-cli configure` fixed #1

**Pull request closed without merging**
